export const Districts: Record<string, string> = {
    "Alipurduar": 'Alipurduar',
    "Bankura": 'Bankura',
    "Birbhum": 'Birbhum',
    "Cooch Behar": 'Cooch Behar',
    "Dakshin Dinajpur": 'Dakshin Dinajpur',
    "Darjeeling": 'Darjeeling',
    "Hooghly": 'Hooghly',
    "Howrah": 'Howrah',
    "Jalpaiguri": 'Jalpaiguri',
    "Kalimpong": 'Kalimpong',
    "Kolkata": 'Kolkata',
    "Malda": 'Malda',
    "Murshidabad": 'Murshidabad',
    "Nadia": 'Nadia',
    "North 24 Parganas": 'North 24 Parganas',
    "Paschim Bardhaman": 'Paschim Bardhaman',
    "Paschim Medinipur": 'Paschim Medinipur',
    "Purba Bardhaman": 'Purba Bardhaman',
    "Purba Medinipur": 'Purba Medinipur',
    "Purulia": 'Purulia',
    "South 24 Parganas": 'South 24 Parganas',
    "Uttar Dinajpur": "Uttar Dinajpur",

  };
